### ISSUE TITLE
出现验证码后报错

### ISSUE THREAD

**Issue by czcxwe** [CyrusRenty/CNKI-download#11]
### config内容：
```
[crawl]
; 爬取及下载开关 0为关闭 1为开启
isDownloadFile = 0
isCrackCode=1
isDetailPage=1
isDownLoadLink=0
stepWaitTime=3

```

### 报错内容
```
正在下载: 高中政治教学中渗透科学精神核心素养路径初探.caj
正在下载: 试论初中语文教学中学生表达能力的培养策略.caj
ERROR:root:出现验证码
Traceback (most recent call last):
  File "/Users/caizhicheng/Desktop/CNKI_download/CNKI-download/main.py", line 144, in parse_page
    tr_table.tr.extract()
AttributeError: 'NoneType' object has no attribute 'tr'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/caizhicheng/Desktop/CNKI_download/CNKI-download/main.py", line 259, in <module>
    if __name__ == '__main__':
  File "/Users/caizhicheng/Desktop/CNKI_download/CNKI-download/main.py", line 253, in main
    search = SearchTools()
  File "/Users/caizhicheng/Desktop/CNKI_download/CNKI-download/main.py", line 98, in search_reference
    self.parse_page(
  File "/Users/caizhicheng/Desktop/CNKI_download/CNKI-download/main.py", line 195, in parse_page
    self.get_another_page(download_page_left)
  File "/Users/caizhicheng/Desktop/CNKI_download/CNKI-download/main.py", line 209, in get_another_page
    self.parse_page(download_page_left, get_res.text)
  File "/Users/caizhicheng/Desktop/CNKI_download/CNKI-download/main.py", line 195, in parse_page
    self.get_another_page(download_page_left)
  File "/Users/caizhicheng/Desktop/CNKI_download/CNKI-download/main.py", line 209, in get_another_page
    self.parse_page(download_page_left, get_res.text)
  File "/Users/caizhicheng/Desktop/CNKI_download/CNKI-download/main.py", line 195, in parse_page
    self.get_another_page(download_page_left)
  File "/Users/caizhicheng/Desktop/CNKI_download/CNKI-download/main.py", line 209, in get_another_page
    self.parse_page(download_page_left, get_res.text)
  File "/Users/caizhicheng/Desktop/CNKI_download/CNKI-download/main.py", line 195, in parse_page
    self.get_another_page(download_page_left)
  File "/Users/caizhicheng/Desktop/CNKI_download/CNKI-download/main.py", line 209, in get_another_page
    self.parse_page(download_page_left, get_res.text)
  File "/Users/caizhicheng/Desktop/CNKI_download/CNKI-download/main.py", line 195, in parse_page
    self.get_another_page(download_page_left)
  File "/Users/caizhicheng/Desktop/CNKI_download/CNKI-download/main.py", line 209, in get_another_page
    self.parse_page(download_page_left, get_res.text)
  File "/Users/caizhicheng/Desktop/CNKI_download/CNKI-download/main.py", line 195, in parse_page
    self.get_another_page(download_page_left)
  File "/Users/caizhicheng/Desktop/CNKI_download/CNKI-download/main.py", line 209, in get_another_page
    self.parse_page(download_page_left, get_res.text)
  File "/Users/caizhicheng/Desktop/CNKI_download/CNKI-download/main.py", line 195, in parse_page
    self.get_another_page(download_page_left)
  File "/Users/caizhicheng/Desktop/CNKI_download/CNKI-download/main.py", line 209, in get_another_page
    self.parse_page(download_page_left, get_res.text)
  File "/Users/caizhicheng/Desktop/CNKI_download/CNKI-download/main.py", line 195, in parse_page
    self.get_another_page(download_page_left)
  File "/Users/caizhicheng/Desktop/CNKI_download/CNKI-download/main.py", line 209, in get_another_page
    self.parse_page(download_page_left, get_res.text)
  File "/Users/caizhicheng/Desktop/CNKI_download/CNKI-download/main.py", line 149, in parse_page
    crack.get_image(self.get_result_url, self.session,
  File "/Users/caizhicheng/Desktop/CNKI_download/CNKI-download/CrackVerifyCode.py", line 34, in get_image
    self.current_url = re.search(r'(.*?)#', current_url).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
```

### 定位到的有关代码
最后一行
```
class CrackCode(object):
    def get_image(self, current_url, session, page_source):
        '''
        获取验证码图片
        '''
        self.header = HEADER
        self.session = session
        # 获得验证码图片地址
        imgurl_pattern_compile = re.compile(r'.*?<img src="(.*?)".*?')
        img_url = re.search(imgurl_pattern_compile, page_source).group(1)
        self.current_url = re.search(r'(.*?)#', current_url).group(1)
```

**Comment by czcxwe** [comment]
### 解决
可能网页已经更改了URL逻辑，所以原来的regx失效了。
```python
# 获得验证码图片地址
        soup = BeautifulSoup(page_source, "html.parser")
        for i in soup.find_all('img'):
            if i.get('title') == '看不清换一张':
                img_url = 'http://kns.cnki.net' + i.get('src')
                print("img_url=" + img_url)
                break
```
