### ISSUE TITLE
验证码出问题

### ISSUE THREAD

**Issue by dengwen168** [CyrusRenty/CNKI-download#13]
采了一百多篇，验证码出问题，提示：
ERROR:root:出现验证码
Traceback (most recent call last):
File "main.py", line 144, in parse_page
tr_table.tr.extract()
AttributeError: 'NoneType' object has no attribute 'tr'

用不用识别码都报错，请帮忙看一下是什么原因？谢谢

**Comment by czcxwe** [comment]
验证码的html结构改了，需要重新分析验证码链接。
bs4 +find_all 可以解决




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"dengwen168"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月29日(星期天) 上午7:48
收件人:&nbsp;"CyrusRenty/CNKI-download"<CNKI-download@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[CyrusRenty/CNKI-download] 验证码出问题 (#13)





 
采了一百多篇，验证码出问题，提示：
 ERROR:root:出现验证码
 Traceback (most recent call last):
 File "main.py", line 144, in parse_page
 tr_table.tr.extract()
 AttributeError: 'NoneType' object has no attribute 'tr'
 
用不用识别码都报错，请帮忙看一下是什么原因？谢谢
