### ISSUE TITLE
无法正常检索论文

### ISSUE THREAD

**Issue by ZehuanZhang** [CyrusRenty/CNKI-download#15]
－－－－－－－－－－－－－－－－－－－－－－－－－－
|　　　　　　　　　　　　　　　　　　　　　　　　　|
|　请选择检索条件：（可多选）　　　　　　　　　　　|
|（ａ）主题　　　（ｂ）关键词　　　（ｃ）篇名　　　|
|（ｄ）摘要　　　（ｅ）全文　　　　（ｆ）被引文献　|
|（ｇ）中图分类号　　　　　　　　　　　　　　　　　|
|　　　　　　　　　　　　　　　　　　　　　　　　　|
－－－－－－－－－－－－－－－－－－－－－－－－－－
请选择（以空格分割，如a c）：c
－－－－－－－－－－－－－－－－－－－－－－－－－－
您选择的是：
 篇名 | 
－－－－－－－－－－－－－－－－－－－－－－－－－－
请输入【篇名】：贫化铀
－－－－－－－－－－－－－－－－－－－－－－－－－－
是否需要规定文献来源（y/n）？n
正在检索中.....
－－－－－－－－－－－－－－－－－－－－－－－－－－
Traceback (most recent call last):
  File "main.py", line 259, in <module>
    main()
  File "main.py", line 253, in main
    search.search_reference(get_uesr_inpt())
  File "main.py", line 99, in search_reference
    self.pre_parse_page(second_get_res.text), second_get_res.text)
  File "main.py", line 107, in pre_parse_page
    page_source).group(1)
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by ufojinfeng** [comment]
是的是的，我也是提示这个，检索不了。

**Comment by Liyuanxigu** [comment]
我也遇到了这个问题

**Comment by zhangjingcode** [comment]
同问

**Comment by braindevices** [comment]
应该是post 坏了，first_post_res返回是`'未传入参数！'`

**Comment by braindevices** [comment]
所有url改为https即可

**Comment by caichen1234567** [comment]
@braindevices  谢谢！ 不报错了

**Comment by songyadong106** [comment]
@caichen1234567  请问这个工程你可以完全用了吗？ 我这边遇到了一些问题，你可以帮忙看一下吗？
  File "main.py", line 99, in search_reference
    self.pre_parse_page(second_get_res.text), second_get_res.text)
  File "main.py", line 188, in parse_page
    self.download_url)
  File "D:\paper_search_program\CNKI-download-master\GetPageDetail.py", line 73, in get_detail_page
    params=params)
  File "D:\anaconda3\lib\site-packages\requests\sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "D:\anaconda3\lib\site-packages\requests\sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\anaconda3\lib\site-packages\requests\sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "D:\anaconda3\lib\site-packages\requests\adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='i.shufang.cnki.net', port=443): Max retries exceeded with url: /KRS/KRSWriteHandler.ashx?referUrl=https%3A%2F%2Fkns.cnki.net%2Fkns%2Fbrief%2Fbrief.aspx%3Fpagename%3DASP.brief_default_result_aspx%26isinEn%3D1%26dbPrefix%3DSCDB%26dbCatalog%3D%25e4%25b8%25ad%25e5%259b%25bd%25e5%25ad%25a6%25e6%259c%25af%25e6%259c%259f%25e5%2588%258a%25e7%25bd%2591%25e7%25bb%259c%25e5%2587%25ba%25e7%2589%2588%25e6%2580%25bb%25e5%25ba%2593%26ConfigFile%3DCJFQ.xml%26research%3Doff%26t%3D1544249384932%26keyValue%3Dpython%26S%3D1%26sorttype%3D%23J_ORDER%26&td=1544605318654&action=file&cnkiUserKey=4e65cf99-0cd7-1bfb-6138-508ac27517e&curUrl=detail.aspx%3FdbCode%3DCJFQ%26fileName%3DXTYY202012037&userName= (Caused by SSLError(CertificateError("hostname 'i.shufang.cnki.net' doesn't match either of '*.cnki.net', 'www.cnki.net', '*.global.cnki.net', '*.oversea.cnki.net', 'big5.book.oversea.cnki.net', 'caj.d.cnki.net', 'caj.oversea.d.cnki.net', 'en.cend.cnki.net', 'eng.tcm.cnki.net', 'gb.book.oversea.cnki.net', 'gb.cend.cnki.net', 'gb.cnbar.cnki.net', 'gb.obaor.cnki.net', 'gb.sczlmz.cnki.net', 'gb.sczlzj.cnki.net', 'gb.tcm.cnki.net', 'kb.tcm.cnki.net', 'oversea.d.cnki.net', 'pdf.d.cnki.net', 'pdf.oversea.d.cnki.net', 'tra.tcm.cnki.net', 'cnki.net'",),))

**Comment by caichen1234567** [comment]
并不能完全用，需要修改



---原始邮件---
发件人: "songyadong106"<notifications@github.com&gt;
发送时间: 2020年12月17日(周四) 下午5:35
收件人: "CyrusRenty/CNKI-download"<CNKI-download@noreply.github.com&gt;;
抄送: "Mention"<mention@noreply.github.com&gt;;"caichen1234567"<1649011989@qq.com&gt;;
主题: Re: [CyrusRenty/CNKI-download] 无法正常检索论文 (#15)




 
@caichen1234567  请问这个工程你可以完全用了吗？ 我这边遇到了一些问题，你可以帮忙看一下吗？
 File "main.py", line 99, in search_reference
 self.pre_parse_page(second_get_res.text), second_get_res.text)
 File "main.py", line 188, in parse_page
 self.download_url)
 File "D:\paper_search_program\CNKI-download-master\GetPageDetail.py", line 73, in get_detail_page
 params=params)
 File "D:\anaconda3\lib\site-packages\requests\sessions.py", line 546, in get
 return self.request('GET', url, **kwargs)
 File "D:\anaconda3\lib\site-packages\requests\sessions.py", line 533, in request
 resp = self.send(prep, **send_kwargs)
 File "D:\anaconda3\lib\site-packages\requests\sessions.py", line 646, in send
 r = adapter.send(request, **kwargs)
 File "D:\anaconda3\lib\site-packages\requests\adapters.py", line 514, in send
 raise SSLError(e, request=request)
 requests.exceptions.SSLError: HTTPSConnectionPool(host='i.shufang.cnki.net', port=443): Max retries exceeded with url: /KRS/KRSWriteHandler.ashx?referUrl=https%3A%2F%2Fkns.cnki.net%2Fkns%2Fbrief%2Fbrief.aspx%3Fpagename%3DASP.brief_default_result_aspx%26isinEn%3D1%26dbPrefix%3DSCDB%26dbCatalog%3D%25e4%25b8%25ad%25e5%259b%25bd%25e5%25ad%25a6%25e6%259c%25af%25e6%259c%259f%25e5%2588%258a%25e7%25bd%2591%25e7%25bb%259c%25e5%2587%25ba%25e7%2589%2588%25e6%2580%25bb%25e5%25ba%2593%26ConfigFile%3DCJFQ.xml%26research%3Doff%26t%3D1544249384932%26keyValue%3Dpython%26S%3D1%26sorttype%3D%23J_ORDER%26&amp;td=1544605318654&amp;action=file&amp;cnkiUserKey=4e65cf99-0cd7-1bfb-6138-508ac27517e&amp;curUrl=detail.aspx%3FdbCode%3DCJFQ%26fileName%3DXTYY202012037&amp;userName= (Caused by SSLError(CertificateError("hostname 'i.shufang.cnki.net' doesn't match either of '.cnki.net', 'www.cnki.net', '.global.cnki.net', '*.oversea.cnki.net', 'big5.book.oversea.cnki.net', 'caj.d.cnki.net', 'caj.oversea.d.cnki.net', 'en.cend.cnki.net', 'eng.tcm.cnki.net', 'gb.book.oversea.cnki.net', 'gb.cend.cnki.net', 'gb.cnbar.cnki.net', 'gb.obaor.cnki.net', 'gb.sczlmz.cnki.net', 'gb.sczlzj.cnki.net', 'gb.tcm.cnki.net', 'kb.tcm.cnki.net', 'oversea.d.cnki.net', 'pdf.d.cnki.net', 'pdf.oversea.d.cnki.net', 'tra.tcm.cnki.net', 'cnki.net'",),))

**Comment by qian-syq** [comment]
还是报错
Traceback (most recent call last):
  File "D:/6-code/PycharmProjects/pythonProject/CNKI-download-master/main.py", line 259, in <module>
    main()
  File "D:/6-code/PycharmProjects/pythonProject/CNKI-download-master/main.py", line 253, in main
    search.search_reference(get_uesr_inpt())
  File "D:/6-code/PycharmProjects/pythonProject/CNKI-download-master/main.py", line 99, in search_reference
    self.pre_parse_page(second_get_res.text), second_get_res.text)
  File "D:/6-code/PycharmProjects/pythonProject/CNKI-download-master/main.py", line 106, in pre_parse_page
    reference_num = re.search(reference_num_pattern_compile,
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by mckChloe** [comment]
> 并不能完全用，需要修改
> […](#)
> ---原始邮件--- 发件人: "songyadong106"<notifications@github.com&gt; 发送时间: 2020年12月17日(周四) 下午5:35 收件人: "CyrusRenty/CNKI-download"<CNKI-download@noreply.github.com&gt;; 抄送: "Mention"<mention@noreply.github.com&gt;;"caichen1234567"<1649011989@qq.com&gt;; 主题: Re: [CyrusRenty/CNKI-download] 无法正常检索论文 (#15) @caichen1234567 请问这个工程你可以完全用了吗？ 我这边遇到了一些问题，你可以帮忙看一下吗？ File "main.py", line 99, in search_reference self.pre_parse_page(second_get_res.text), second_get_res.text) File "main.py", line 188, in parse_page self.download_url) File "D:\paper_search_program\CNKI-download-master\GetPageDetail.py", line 73, in get_detail_page params=params) File "D:\anaconda3\lib\site-packages\requests\sessions.py", line 546, in get return self.request('GET', url, **kwargs) File "D:\anaconda3\lib\site-packages\requests\sessions.py", line 533, in request resp = self.send(prep, **send_kwargs) File "D:\anaconda3\lib\site-packages\requests\sessions.py", line 646, in send r = adapter.send(request, **kwargs) File "D:\anaconda3\lib\site-packages\requests\adapters.py", line 514, in send raise SSLError(e, request=request) requests.exceptions.SSLError: HTTPSConnectionPool(host='i.shufang.cnki.net', port=443): Max retries exceeded with url: /KRS/KRSWriteHandler.ashx?referUrl=https%3A%2F%2Fkns.cnki.net%2Fkns%2Fbrief%2Fbrief.aspx%3Fpagename%3DASP.brief_default_result_aspx%26isinEn%3D1%26dbPrefix%3DSCDB%26dbCatalog%3D%25e4%25b8%25ad%25e5%259b%25bd%25e5%25ad%25a6%25e6%259c%25af%25e6%259c%259f%25e5%2588%258a%25e7%25bd%2591%25e7%25bb%259c%25e5%2587%25ba%25e7%2589%2588%25e6%2580%25bb%25e5%25ba%2593%26ConfigFile%3DCJFQ.xml%26research%3Doff%26t%3D1544249384932%26keyValue%3Dpython%26S%3D1%26sorttype%3D%23J_ORDER%26&amp;td=1544605318654&amp;action=file&amp;cnkiUserKey=4e65cf99-0cd7-1bfb-6138-508ac27517e&amp;curUrl=detail.aspx%3FdbCode%3DCJFQ%26fileName%3DXTYY202012037&amp;userName= (Caused by SSLError(CertificateError("hostname 'i.shufang.cnki.net' doesn't match either of '.cnki.net', '[www.cnki.net](http://www.cnki.net)', '.global.cnki.net', '*.oversea.cnki.net', 'big5.book.oversea.cnki.net', 'caj.d.cnki.net', 'caj.oversea.d.cnki.net', 'en.cend.cnki.net', 'eng.tcm.cnki.net', 'gb.book.oversea.cnki.net', 'gb.cend.cnki.net', 'gb.cnbar.cnki.net', 'gb.obaor.cnki.net', 'gb.sczlmz.cnki.net', 'gb.sczlzj.cnki.net', 'gb.tcm.cnki.net', 'kb.tcm.cnki.net', 'oversea.d.cnki.net', 'pdf.d.cnki.net', 'pdf.oversea.d.cnki.net', 'tra.tcm.cnki.net', 'cnki.net'",),)) — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

请问一下要怎么修改呢？

**Comment by qian-syq** [comment]
> > 并不能完全用，需要修改
> > […](#)
> > ---原始邮件--- 发件人: "songyadong106"<[notifications@github.com](mailto:notifications@github.com)> 发送时间: 2020年12月17日(周四) 下午5:35 收件人: "CyrusRenty/CNKI-download"<[CNKI-download@noreply.github.com](mailto:CNKI-download@noreply.github.com)>; 抄送: "Mention"<[mention@noreply.github.com](mailto:mention@noreply.github.com)>;"caichen1234567"<[1649011989@qq.com](mailto:1649011989@qq.com)>; 主题: Re: [CyrusRenty/CNKI-download] 无法正常检索论文 (#15) @caichen1234567 请问这个工程你可以完全用了吗？ 我这边遇到了一些问题，你可以帮忙看一下吗？ File "main.py", line 99, in search_reference self.pre_parse_page(second_get_res.text), second_get_res.text) File "main.py", line 188, in parse_page self.download_url) File "D:\paper_search_program\CNKI-download-master\GetPageDetail.py", line 73, in get_detail_page params=params) File "D:\anaconda3\lib\site-packages\requests\sessions.py", line 546, in get return self.request('GET', url, **kwargs) File "D:\anaconda3\lib\site-packages\requests\sessions.py", line 533, in request resp = self.send(prep, **send_kwargs) File "D:\anaconda3\lib\site-packages\requests\sessions.py", line 646, in send r = adapter.send(request, **kwargs) File "D:\anaconda3\lib\site-packages\requests\adapters.py", line 514, in send raise SSLError(e, request=request) requests.exceptions.SSLError: HTTPSConnectionPool(host='i.shufang.cnki.net', port=443): Max retries exceeded with url: /KRS/KRSWriteHandler.ashx?referUrl=https%3A%2F%2Fkns.cnki.net%2Fkns%2Fbrief%2Fbrief.aspx%3Fpagename%3DASP.brief_default_result_aspx%26isinEn%3D1%26dbPrefix%3DSCDB%26dbCatalog%3D%25e4%25b8%25ad%25e5%259b%25bd%25e5%25ad%25a6%25e6%259c%25af%25e6%259c%259f%25e5%2588%258a%25e7%25bd%2591%25e7%25bb%259c%25e5%2587%25ba%25e7%2589%2588%25e6%2580%25bb%25e5%25ba%2593%26ConfigFile%3DCJFQ.xml%26research%3Doff%26t%3D1544249384932%26keyValue%3Dpython%26S%3D1%26sorttype%3D%23J_ORDER%26&td=1544605318654&action=file&cnkiUserKey=4e65cf99-0cd7-1bfb-6138-508ac27517e&curUrl=detail.aspx%3FdbCode%3DCJFQ%26fileName%3DXTYY202012037&userName= (Caused by SSLError(CertificateError("hostname 'i.shufang.cnki.net' doesn't match either of '.cnki.net', '[www.cnki.net](http://www.cnki.net)', '.global.cnki.net', '*.oversea.cnki.net', 'big5.book.oversea.cnki.net', 'caj.d.cnki.net', 'caj.oversea.d.cnki.net', 'en.cend.cnki.net', 'eng.tcm.cnki.net', 'gb.book.oversea.cnki.net', 'gb.cend.cnki.net', 'gb.cnbar.cnki.net', 'gb.obaor.cnki.net', 'gb.sczlmz.cnki.net', 'gb.sczlzj.cnki.net', 'gb.tcm.cnki.net', 'kb.tcm.cnki.net', 'oversea.d.cnki.net', 'pdf.d.cnki.net', 'pdf.oversea.d.cnki.net', 'tra.tcm.cnki.net', 'cnki.net'",),)) — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> 请问一下要怎么修改呢？

不清楚，没有改成功
