### ISSUE TITLE
请教遇到这个问题怎么办？十分感谢

### ISSUE THREAD

**Issue by Nickashang** [CyrusRenty/CNKI-download#17]
> Traceback (most recent call last):
  File "F:\Python\CNKI-爬虫download\main.py", line 27, in <module>
    from GetPageDetail import page_detail
  File "F:\Python\CNKI-爬虫download\GetPageDetail.py", line 203, in <module>
    page_detail = PageDetail()
  File "F:\Python\CNKI-爬虫download\GetPageDetail.py", line 39, in __init__
    if config.crawl_isDownLoadLink == '1':
  File "F:\Python\CNKI-爬虫download\GetConfig.py", line 30, in __get__
    value = self.func(instance)
  File "F:\Python\CNKI-爬虫download\GetConfig.py", line 75, in crawl_isDownLoadLink
    return int(self.conf.get('crawl', 'isDownLoadLink'))
  File "F:\Anaconda\envs\tensorflow-gpu\lib\configparser.py", line 781, in get
    d = self._unify_values(section, vars)
  File "F:\Anaconda\envs\tensorflow-gpu\lib\configparser.py", line 1141, in _unify_values
    raise NoSectionError(section)
configparser.NoSectionError: No section: 'crawl'

**Comment by ylyy** [comment]
我也遇到了这个问题

**Comment by caichen1234567** [comment]
.ini路径问题，进去设置一下路径就好

**Comment by songyadong106** [comment]
![Uploading image.png…]()

**Comment by songyadong106** [comment]
Traceback (most recent call last):
  File "main.py", line 259, in <module>
    main()
  File "main.py", line 253, in main
    search.search_reference(get_uesr_inpt())
  File "main.py", line 99, in search_reference
    self.pre_parse_page(second_get_res.text), second_get_res.text)
  File "main.py", line 107, in pre_parse_page
    page_source).group(1)
AttributeError: 'NoneType' object has no attribute 'group'

我想问一下，这个是什么错误呢？  另外[crawl] 这个参数代表什么呢？  希望您的解答，谢谢！！！！！！！！！

**Comment by CyrusRenty** [comment]
> 
> 
> > Traceback (most recent call last):
> > File "F:\Python\CNKI-爬虫download\main.py", line 27, in 
> > from GetPageDetail import page_detail
> > File "F:\Python\CNKI-爬虫download\GetPageDetail.py", line 203, in 
> > page_detail = PageDetail()
> > File "F:\Python\CNKI-爬虫download\GetPageDetail.py", line 39, in **init**
> > if config.crawl_isDownLoadLink == '1':
> > File "F:\Python\CNKI-爬虫download\GetConfig.py", line 30, in **get**
> > value = self.func(instance)
> > File "F:\Python\CNKI-爬虫download\GetConfig.py", line 75, in crawl_isDownLoadLink
> > return int(self.conf.get('crawl', 'isDownLoadLink'))
> > File "F:\Anaconda\envs\tensorflow-gpu\lib\configparser.py", line 781, in get
> > d = self._unify_values(section, vars)
> > File "F:\Anaconda\envs\tensorflow-gpu\lib\configparser.py", line 1141, in _unify_values
> > raise NoSectionError(section)
> > configparser.NoSectionError: No section: 'crawl'

配置文件路径需要设置正确

**Comment by zhuoruofuqu** [comment]
Traceback (most recent call last):
  File "C:/Users/ASUS/PycharmProjects/1111111/知网/CNKI-download-master/main.py", line 259, in <module>
    main()
  File "C:/Users/ASUS/PycharmProjects/1111111/知网/CNKI-download-master/main.py", line 253, in main
    search.search_reference(get_uesr_inpt())
  File "C:/Users/ASUS/PycharmProjects/1111111/知网/CNKI-download-master/main.py", line 99, in search_reference
    self.pre_parse_page(second_get_res.text), second_get_res.text)
  File "C:/Users/ASUS/PycharmProjects/1111111/知网/CNKI-download-master/main.py", line 106, in pre_parse_page
    reference_num = re.search(reference_num_pattern_compile,
AttributeError: 'NoneType' object has no attribute 'group'
遇到此问题，不知如何修改，希望得到您的解答，万分感谢！！！！！

**Comment by zzxx59342506** [comment]
> Traceback (most recent call last):
> File "main.py", line 259, in
> main()
> File "main.py", line 253, in main
> search.search_reference(get_uesr_inpt())
> File "main.py", line 99, in search_reference
> self.pre_parse_page(second_get_res.text), second_get_res.text)
> File "main.py", line 107, in pre_parse_page
> page_source).group(1)
> AttributeError: 'NoneType' object has no attribute 'group'
> 
> 我想问一下，这个是什么错误呢？ 另外[crawl] 这个参数代表什么呢？ 希望您的解答，谢谢！！！！！！！！！

我也遇到这个问题了
