### ISSUE TITLE
检索论文出现问题

### ISSUE THREAD

**Issue by songyadong106** [CyrusRenty/CNKI-download#20]
检索到69条结果，全部下载大约需要00小时05分钟45秒。
是否要全部下载（y/n）?y
正在下载: 基于文字识别技术的作业自动批改系统.caj
Traceback (most recent call last):
  File "main.py", line 259, in <module>
    main()
  File "main.py", line 253, in main
    search.search_reference(get_uesr_inpt())
  File "main.py", line 99, in search_reference
    self.pre_parse_page(second_get_res.text), second_get_res.text)
  File "main.py", line 188, in parse_page
    self.download_url)
  File "D:\paper_search_program\CNKI-download-master\GetPageDetail.py", line 80, in get_detail_page
    self.pars_page(get_res.text)
  File "D:\paper_search_program\CNKI-download-master\GetPageDetail.py", line 89, in pars_page
    orgn_list = soup.find(name='div', class_='orgn').find_all('a')
AttributeError: 'NoneType' object has no attribute 'find_all'

这个该怎么解决啊？  博主，希望可以解答一波！！！！！！！！谢谢！！！

**Comment by PaffxAroma** [comment]
同求此问题解决方案
