### ISSUE TITLE
有相似无法检索的情况

### ISSUE THREAD

**Issue by zenanpu** [CyrusRenty/CNKI-download#22]
是否需要规定文献来源（y/n）？n
正在检索中.....
－－－－－－－－－－－－－－－－－－－－－－－－－－
Traceback (most recent call last):
  File "/Users/puzenan/Desktop/CNKI-download-master/main.py", line 259, in <module>
    main()
  File "/Users/puzenan/Desktop/CNKI-download-master/main.py", line 253, in main
    search.search_reference(get_uesr_inpt())
  File "/Users/puzenan/Desktop/CNKI-download-master/main.py", line 99, in search_reference
    self.pre_parse_page(second_get_res.text), second_get_res.text)
  File "/Users/puzenan/Desktop/CNKI-download-master/main.py", line 106, in pre_parse_page
    reference_num = re.search(reference_num_pattern_compile,
AttributeError: 'NoneType' object has no attribute 'group'

求助大佬

**Comment by zenanpu** [comment]
是不是需要异步加载的方式(XHR或者js)

**Comment by zjmazy** [comment]
我也是这个问题
