### ISSUE TITLE
请教出现这些是什么问题？万分感谢

### ISSUE THREAD

**Issue by happylike** [CyrusRenty/CNKI-download#23]
Traceback (most recent call last):
  File "C:\Users\Yuchl\Downloads\CNKI-download-master\main.py", line 259, in <module>
    main()
  File "C:\Users\Yuchl\Downloads\CNKI-download-master\main.py", line 253, in main
    search.search_reference(get_uesr_inpt())
  File "C:\Users\Yuchl\Downloads\CNKI-download-master\main.py", line 99, in search_reference
    self.pre_parse_page(second_get_res.text), second_get_res.text)
  File "C:\Users\Yuchl\Downloads\CNKI-download-master\main.py", line 106, in pre_parse_page
    reference_num = re.search(reference_num_pattern_compile,
AttributeError: 'NoneType' object has no attribute **'group'******

**Comment by happylike** [comment]
已解决，应该是遗留问题看了别的issue，解决方法是将main.py中的所有url改为https即可
