### ISSUE TITLE
无法搜索

### ISSUE THREAD

**Issue by barnett2010** [CyrusRenty/CNKI-download#38]
python main.py
－－－－－－－－－－－－－－－－－－－－－－－－－－
|　　　　　　　　　　　　　　　　　　　　　　　　　|
|　请选择检索条件：（可多选）　　　　　　　　　　　|
|（ａ）主题　　　（ｂ）关键词　　　（ｃ）篇名　　　|
|（ｄ）摘要　　　（ｅ）全文　　　　（ｆ）被引文献　|
|（ｇ）中图分类号　　　　　　　　　　　　　　　　　|
|　　　　　　　　　　　　　　　　　　　　　　　　　|
－－－－－－－－－－－－－－－－－－－－－－－－－－
请选择（以空格分割，如a c）：c
－－－－－－－－－－－－－－－－－－－－－－－－－－
您选择的是：
 篇名 |
－－－－－－－－－－－－－－－－－－－－－－－－－－
请输入【篇名】：汉服
－－－－－－－－－－－－－－－－－－－－－－－－－－
是否需要规定文献来源（y/n）？n
正在检索中.....
－－－－－－－－－－－－－－－－－－－－－－－－－－
Traceback (most recent call last):
  File "main.py", line 259, in <module>
    main()
  File "main.py", line 253, in main
    search.search_reference(get_uesr_inpt())
  File "main.py", line 99, in search_reference
    self.pre_parse_page(second_get_res.text), second_get_res.text)
  File "main.py", line 107, in pre_parse_page
    page_source).group(1)
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by YinZhaokai** [comment]
试试将所有文件中的"http"替换成"https"

**Comment by OctopusLian** [comment]
我也遇到了，已经换了，还是不行
