### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'find_all'这个怎么解决呀

### ISSUE THREAD

**Issue by piao0623** [CyrusRenty/CNKI-download#40]
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\CNKI-download\main.py", line 259, in <module>
    main()
  File "C:\Users\Administrator\Desktop\CNKI-download\main.py", line 253, in main
    search.search_reference(get_uesr_inpt())
  File "C:\Users\Administrator\Desktop\CNKI-download\main.py", line 98, in search_reference
    self.parse_page(
  File "C:\Users\Administrator\Desktop\CNKI-download\main.py", line 186, in parse_page
    page_detail.get_detail_page(self.session, self.get_result_url,
  File "C:\Users\Administrator\Desktop\CNKI-download\GetPageDetail.py", line 80, in get_detail_page
    self.pars_page(get_res.text)
  File "C:\Users\Administrator\Desktop\CNKI-download\GetPageDetail.py", line 89, in pars_page
    orgn_list = soup.find(name='div', class_='orgn').find_all('a')
AttributeError: 'NoneType' object has no attribute 'find_all'

**Comment by barnett2010** [comment]
是否需要规定文献来源（y/n）？n
正在检索中.....
－－－－－－－－－－－－－－－－－－－－－－－－－－
Traceback (most recent call last):
  File "main.py", line 259, in <module>
    main()
  File "main.py", line 253, in main
    search.search_reference(get_uesr_inpt())
  File "main.py", line 99, in search_reference
    self.pre_parse_page(second_get_res.text), second_get_res.text)
  File "main.py", line 107, in pre_parse_page
    page_source).group(1)
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by PPF12138** [comment]
> 是否需要规定文献来源（y/n）？n 正在检索中..... －－－－－－－－－－－－－－－－－－－－－－－－－－ Traceback (most recent call last): File "main.py", line 259, in main() File "main.py", line 253, in main search.search_reference(get_uesr_inpt()) File "main.py", line 99, in search_reference self.pre_parse_page(second_get_res.text), second_get_res.text) File "main.py", line 107, in pre_parse_page page_source).group(1) AttributeError: 'NoneType' object has no attribute 'group'

试试将所有文件中的"http"都替换成"https"

**Comment by DavidLeexxxx** [comment]
> Traceback (most recent call last): File "C:\Users\Administrator\Desktop\CNKI-download\main.py", line 259, in main() File "C:\Users\Administrator\Desktop\CNKI-download\main.py", line 253, in main search.search_reference(get_uesr_inpt()) File "C:\Users\Administrator\Desktop\CNKI-download\main.py", line 98, in search_reference self.parse_page( File "C:\Users\Administrator\Desktop\CNKI-download\main.py", line 186, in parse_page page_detail.get_detail_page(self.session, self.get_result_url, File "C:\Users\Administrator\Desktop\CNKI-download\GetPageDetail.py", line 80, in get_detail_page self.pars_page(get_res.text) File "C:\Users\Administrator\Desktop\CNKI-download\GetPageDetail.py", line 89, in pars_page orgn_list = soup.find(name='div', class_='orgn').find_all('a') AttributeError: 'NoneType' object has no attribute 'find_all'

请问这个问题您后面解决了么
