### ISSUE TITLE
非常抱歉打扰，但是这个问题困扰了我许久，期待您的解答

### ISSUE THREAD

**Issue by Flechazojn** [CyrusRenty/CNKI-download#45]
请输入【主题】：python
请输入【篇名】：网络
请输入【篇名】条件类型:（ａ）并且　（ｂ）或者　（ｃ）不含 c
－－－－－－－－－－－－－－－－－－－－－－－－－－
是否需要规定文献来源（y/n）？y
输入文献来源期刊名称：电子技术与软件工程
正在检索中.....
－－－－－－－－－－－－－－－－－－－－－－－－－－
检索到85条结果，全部下载大约需要00小时07分钟05秒。
是否要全部下载（y/n）?n
请输入需要下载的数量：1
开始下载前1页所有文件，预计用时00小时01分钟40秒
－－－－－－－－－－－－－－－－－－－－－－－－－－
正在下载: Python在商品销售数据分析中的使用.cajTraceback (most recent call last):
  File "D:\idea\Data_mining\venv\lib\site-packages\urllib3\connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "D:\idea\Data_mining\venv\lib\site-packages\urllib3\util\connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "C:\Users\11815\AppData\Local\Programs\Python\Python310\lib\socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\idea\Data_mining\venv\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "D:\idea\Data_mining\venv\lib\site-packages\urllib3\connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "D:\idea\Data_mining\venv\lib\site-packages\urllib3\connection.py", line 239, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "C:\Users\11815\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\11815\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\11815\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\11815\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1037, in _send_output
    self.send(msg)
  File "C:\Users\11815\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 975, in send
    self.connect()
  File "D:\idea\Data_mining\venv\lib\site-packages\urllib3\connection.py", line 205, in connect
    conn = self._new_conn()
  File "D:\idea\Data_mining\venv\lib\site-packages\urllib3\connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x000002B698451D20>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\idea\Data_mining\venv\lib\site-packages\requests\adapters.py", line 489, in send
    resp = conn.urlopen(
  File "D:\idea\Data_mining\venv\lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "D:\idea\Data_mining\venv\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='i.shufang.cnki.net', port=80): Max retries exceeded with url: /KRS/KRSWriteHandler.ashx?curUrl=detail.aspx%3FdbCode%3DCJFQ%26fileName%3DDZRU202210049&referUrl=https%3A%2F%2Fkns.cnki.net%2Fkns%2Fbrief%2Fbrief.aspx%3Fpagename%3DASP.brief_default_result_aspx%26isinEn%3D1%26dbPrefix%3DSCDB%26dbCatalog%3D%25e4%25b8%25ad%25e5%259b%25bd%25e5%25ad%25a6%25e6%259c%25af%25e6%259c%259f%25e5%2588%258a%25e7%25bd%2591%25e7%25bb%259c%25e5%2587%25ba%25e7%2589%2588%25e6%2580%25bb%25e5%25ba%2593%26ConfigFile%3DCJFQ.xml%26research%3Doff%26t%3D1544249384932%26keyValue%3Dpython%26S%3D1%26sorttype%3D%23J_ORDER%26&cnkiUserKey=726a6f53-1896-b19c-b08a-c7edde6fcf0&action=file&userName=&td=1544605318654 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002B698451D20>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\idea\Data_mining\数据挖掘\zhiwang\main.py", line 249, in <module>
    main()
  File "D:\idea\Data_mining\数据挖掘\zhiwang\main.py", line 243, in main
    search.search_reference(get_uesr_inpt())
  File "D:\idea\Data_mining\数据挖掘\zhiwang\main.py", line 88, in search_reference
    self.parse_page(
  File "D:\idea\Data_mining\数据挖掘\zhiwang\main.py", line 176, in parse_page
    page_detail.get_detail_page(self.session, self.get_result_url,
  File "D:\idea\Data_mining\数据挖掘\zhiwang\GetPageDetail.py", line 70, in get_detail_page
    self.session.get(
  File "D:\idea\Data_mining\venv\lib\site-packages\requests\sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
  File "D:\idea\Data_mining\venv\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\idea\Data_mining\venv\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "D:\idea\Data_mining\venv\lib\site-packages\requests\adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='i.shufang.cnki.net', port=80): Max retries exceeded with url: /KRS/KRSWriteHandler.ashx?curUrl=detail.aspx%3FdbCode%3DCJFQ%26fileName%3DDZRU202210049&referUrl=https%3A%2F%2Fkns.cnki.net%2Fkns%2Fbrief%2Fbrief.aspx%3Fpagename%3DASP.brief_default_result_aspx%26isinEn%3D1%26dbPrefix%3DSCDB%26dbCatalog%3D%25e4%25b8%25ad%25e5%259b%25bd%25e5%25ad%25a6%25e6%259c%25af%25e6%259c%259f%25e5%2588%258a%25e7%25bd%2591%25e7%25bb%259c%25e5%2587%25ba%25e7%2589%2588%25e6%2580%25bb%25e5%25ba%2593%26ConfigFile%3DCJFQ.xml%26research%3Doff%26t%3D1544249384932%26keyValue%3Dpython%26S%3D1%26sorttype%3D%23J_ORDER%26&cnkiUserKey=726a6f53-1896-b19c-b08a-c7edde6fcf0&action=file&userName=&td=1544605318654 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002B698451D20>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

**Comment by DavidLeexxxx** [comment]
我也遇到了这个问题，请问解决了么
