### ISSUE TITLE
下载指定篇名的论文下不了啊

### ISSUE THREAD

**Issue by gityfx2018** [CyrusRenty/CNKI-download#8]
应该时没搜到   主题词 关键词等单一搜索都是报这个错
Traceback (most recent call last):
  File "C:/Users/Lenovo/Downloads/CNKI-download-master/CNKI-download-master/main.py", line 246, in <module>
    main()
  File "C:/Users/Lenovo/Downloads/CNKI-download-master/CNKI-download-master/main.py", line 240, in main
    search.search_reference(get_uesr_inpt())
  File "C:/Users/Lenovo/Downloads/CNKI-download-master/CNKI-download-master/main.py", line 87, in search_reference
    second_get_res.text).group(1)
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by caichen1234567** [comment]
.ini配置文件路径
