### ISSUE TITLE
当搜索结果不够20个（一页）的时候会报错，希望能解决一下

### ISSUE THREAD

**Issue by irimsky** [CyrusRenty/CNKI-download#9]
```
正在检索中.....
－－－－－－－－－－－－－－－－－－－－－－－－－－
Traceback (most recent call last):
  File "/Users/irimsky/Downloads/CNKI-download-master/main.py", line 254, in <module>
    main()
  File "/Users/irimsky/Downloads/CNKI-download-master/main.py", line 248, in main
    search.search_reference(get_uesr_inpt())
  File "/Users/irimsky/Downloads/CNKI-download-master/main.py", line 92, in search_reference
    second_get_res.text).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
```

**Comment by CyrusRenty** [comment]
我看到你已经解决了，最近一直没时间维护这个项目，谢谢你！
